### Pytorch

#### Devloped by Facebook AI research lab (FAIR) in 2016
#### PyTorch is an optimized tensor library primarily used for Deep Learning applications using GPUs and CPUs.
#### Written in Python, CUDA, C++
#### PyTorch is similar to NumPy in the way that it manages computations, but has a strong GPU support.
#### 

### Tensors

#### PyTorch is a library for processing tensors. A tensor is a fundamental unit of data. It can be a number, vector, matrix, or any n-dimensional array. It is similar to Numpy arrays.
#### Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.
#### Tensors are (kind of) like np.arrays.
#### All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [5]:
import torch
import numpy as np

In [6]:
## Check version of torch
torch.__version__

'1.8.1'

In [11]:
lst=[1,2,3,4,5,7,8,2,9]
arr=np.array(lst)
arr                 #Here datatype is array

array([1, 2, 3, 4, 5, 7, 8, 2, 9])

In [20]:
## Create Tensors

torch.zeros(2,3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.ones(2,3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [22]:
tens = torch.tensor([2,6,4,7,8], dtype=torch.float)

In [19]:
## Convert numpy array to pytorch tensors

tensors=torch.from_numpy(arr)
print(tensors)             #Here datatype is torch tensor

## OR

tensors_1 = torch.tensor(arr)
print(tensors_1)

## Difference between both methods is:
## from_numpy tensor and arr will have the same memory location. So if I make any changes in tensor, original array will also change.
## torch.tensor will make copy of the original array and it will not affect the original one.

tensor([1, 2, 3, 4, 5, 7, 8, 2, 9], dtype=torch.int32)
tensor([1, 2, 3, 4, 5, 7, 8, 2, 9], dtype=torch.int32)


In [15]:
#In tensors, we can access any element similar to numpy.
# For example:

print(tensors[5])           #Element at specific index
print(tensors[2:8])         #Slicing

tensor(7, dtype=torch.int32)
tensor([3, 4, 5, 7, 8, 2], dtype=torch.int32)


In [23]:
## Arithmetic Operation

In [27]:
a = torch.tensor([1,5,7], dtype=torch.float)
b = torch.tensor([5,8,2], dtype=torch.float)
print(a + b)

## or

print(torch.add(a,b))

c=torch.zeros(3)

torch.add(a,b,out=c)      # This will store output in c variable. It should be of the same dimension as expected output.

print(c)

tensor([ 6., 13.,  9.])
tensor([ 6., 13.,  9.])
tensor([ 6., 13.,  9.])


In [29]:
c.sum()            # Sum of all elements

tensor(28.)

In [30]:
a.mul(b)           # Normal Multiplication of elements of two tensors

tensor([ 5., 40., 14.])

In [31]:
a.dot(b)            # Dot product of two tensors

tensor(59.)

In [32]:
a@b

tensor(59.)

In [34]:
## For two dimensional tensors Matrix Multiplication

In [35]:
a = torch.tensor([[2,5,3],[6,3,8]], dtype=torch.float)
b = torch.tensor([[2,5],[6,4],[1,9]], dtype=torch.float)

In [37]:
print(torch.matmul(a,b))

## OR

print(torch.mm(a,b))

## OR

print(a@b)

tensor([[ 37.,  57.],
        [ 38., 114.]])
tensor([[ 37.,  57.],
        [ 38., 114.]])
tensor([[ 37.,  57.],
        [ 38., 114.]])
